on: [push, pull_request]

name: test

jobs:
  test:
    name: test
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ghc:
          - '8.4.4'
          - '8.6.5'
          - '8.8.3'
          - '8.10.1'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.2'
      - run: cabal new-update
      - run: cabal new-test
  hlint:
    name: lint .hs
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - run: docker run -v $(pwd):/work coorde/hlint:2.2.11 hlint --git
  hs-fmt:
    name: check .hs style
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      # TODO: Use the next version of brittany that supports PatternSynonyms
      - run: |
          find . -name '*.hs' \
            -not -path '*/Language/Sonic/Parser/Internal/Error.hs' \
            -exec docker run -v $(pwd):/work herpinc/brittany:0.12.1.1 brittany --check-mode {} +
  cabal-fmt:
    name: check .cabal style
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - run: find . -name '*.cabal' -exec docker run -v $(pwd):/work coorde/cabal-fmt:0.1.2 cabal-fmt -i {} +
      - run: git diff --exit-code
  shellcheck:
    name: check .sh
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - run: find script -type f -name '*.sh' | xargs docker run -v $(pwd):/mnt koalaman/shellcheck:v0.7.1
